import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, relative } from 'node:path';

/**
 * Generate the service worker and web app manifest against the real build output.
 *
 * Written by hand rather than by `vite-plugin-pwa` for one reason worth stating: the plugin brings
 * Workbox, and the entire offline requirement here is "cache these fourteen files and serve them
 * back". A dependency whose configuration surface is larger than the thing it configures is a
 * liability, and this file is short enough to read.
 *
 * Offline is not a nice-to-have for this tool. The whole premise is that documents never leave the
 * browser (§8) — a validator that stops working on a train contradicts its own security story.
 */

const dist = new URL('../dist/', import.meta.url).pathname;

async function filesUnder(directory) {
  const out = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) out.push(...(await filesUnder(path)));
    else out.push(path);
  }
  return out;
}

const base = process.env.BASE_PATH ?? '/x-editor/';
const files = (await filesUnder(dist))
  .map((path) => relative(dist, path))
  // Source maps are large and only useful with devtools open, which is not an offline scenario.
  .filter((path) => !path.endsWith('.map') && path !== 'sw.js' && path !== 'manifest.webmanifest')
  .sort();

// The cache name carries a hash of everything in it, so a new build invalidates the old cache
// wholesale. Versioning by hand is how a stale asset survives three deploys.
const hash = createHash('sha256');
for (const path of files) hash.update(path).update(await readFile(join(dist, path)));
const version = hash.digest('hex').slice(0, 12);

const assets = files.map((path) => `${base}${path}`);
assets.push(base);

const sw = `// Generated by scripts/build-sw.mjs — do not edit.
const CACHE = 'x-editor-${version}';
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (event) => {
  // Skip waiting: there is no cross-tab state to corrupt, and leaving a user on last week's build
  // until they close every tab is a worse failure than a reload.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Cache-first. Every asset is content-hashed by Vite, so a cache hit is never stale; the one
  // unhashed entry is the document itself, which the activate handler above drops on every build.
  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit !== undefined) return hit;
      return fetch(request).catch(() =>
        // A navigation that misses the cache offline still gets the app shell, so a deep link does
        // not become a browser error page.
        request.mode === 'navigate' ? caches.match('${base}') : Promise.reject(new Error('offline')),
      );
    }),
  );
});
`;

const manifest = {
  name: 'x-editor — XML, XSD and Schematron',
  short_name: 'x-editor',
  description:
    'A tree-based editor for XML, XSD and Schematron that tells you what you are allowed to put where. Documents never leave the browser.',
  start_url: base,
  scope: base,
  display: 'standalone',
  background_color: '#0f1115',
  theme_color: '#0f1115',
  icons: [{ src: `${base}favicon.svg`, sizes: 'any', type: 'image/svg+xml', purpose: 'any' }],
};

await writeFile(join(dist, 'sw.js'), sw);
await writeFile(join(dist, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2));

console.log(`✓ service worker caches ${assets.length} entries (x-editor-${version})`);
